### PR TITLE
Start process of renaming to stograde

### PR DESCRIPTION
**Pull request by maxnz**

### CODE REVIEW

**Comment by maxnz** [comment]
Ok thanks. I'll let you know

**Comment by maxnz** [comment]
I think this might be ready. One I haven't changed are any links to the github repo.

**Comment by hawkrives** [comment]
I'll try to remember to look at this on Tuesday.

**Comment by maxnz** [comment]
Would we be able to finish this by the end of this weekend?

**Comment by hawkrives** [comment]
Yes

**Comment by maxnz** [comment]
Any progress?

**Comment by maxnz** [comment]
Do we need to make a new release for it to be pushed to PyPi? And does .travis.yml need to be updated?
https://github.com/StoDevX/stograde/blob/79d71641fa105c02407d0595243c478aee5580dd/.travis.yml#L40

**Comment by hawkrives** [comment]
Apparently Travis has broken entirely, so we’ll need to either fix it or port the config to GitHub Actions before we can release

**Pull request merged**
